#pragma config(StandardModel, "RVW Anemobot")
#pragma config(RenamedStdModelMotor, motorA, armMotor)
#pragma config(RenamedStdModelSensor, S3, colorSensor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int map[9][7];
	int i,x,y=0;

	//Initialise all elements of map to 0 (White square)
	for (x=0; x<9; x++)
	{
		for (y=0; y<7; y++)
		{
			map[x][y]=0;
		}
	}

	//Start loop to detect edges
	while (i<4)
	{
    setMotorSync(motorB, motorC, 0, 30);	//Both motors move at 30% speed

    if (SensorValue[colorSensor]>47)	//if robot sees black
    {
    	setMotorSync(motorB, motorC, 0, 30);	//keep moving forward at 30%
    	clearTimer(T1); //start timer from 0

    	//while timer less than .5seconds, if black line is seen again
    	while (time1[T1] < 0500)
    	{
    		if (SensorValue[colorSensor]>47)
    		{
	    		//Reverse robot for half a second
	    		setMotorSync(motorB, motorC, 0, -30);
	    		sleep(0500);

	    		//Turn right
	    		setMotorSpeed(leftMotor, 40);		//Set leftMotor to 40% power forward (40)
					setMotorSpeed(rightMotor, -40);		//Set rightMotor to 40% power reverse (-40)
					sleep(0430);

					i++;
				}//end if
			}//end while
		}//end if
	}//end while

}//end main
